name: Feature
description: Improve an existing feature or behavior
title: '[FEATURE] '
labels: ['feature']
body:
  - type: textarea
    id: summary
    attributes:
      label: Feature Description
      description: Describe the improvement you’d like to see
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature valuable?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative approaches you’ve thought about
